# ==========================================================
# FastAPI Docker Image
# ==========================================================

FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# ----------------------------------------------------------
# System Dependencies
# ----------------------------------------------------------

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# ----------------------------------------------------------
# Install Python Packages
# ----------------------------------------------------------

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

# ----------------------------------------------------------
# Copy Project
# ----------------------------------------------------------

COPY . .

# ----------------------------------------------------------
# Expose Port
# ----------------------------------------------------------

EXPOSE 8000

# ----------------------------------------------------------
# Start FastAPI
# ----------------------------------------------------------

CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]